const state={
  page:'dashboard',
  bookings:JSON.parse(localStorage.getItem('s1-bookings')||'[]'),
  trips:[
    {id:'TRP-1001',customer:'السعودية للحديد',origin:'جدة',destination:'الرياض',truck:'TRK-025',driver:'محمد سالم',carrier:'ناقل الوطنية',status:'في الطريق',value:5200},
    {id:'TRP-1002',customer:'الخليج للأغذية',origin:'الرياض',destination:'الدمام',truck:'TRK-014',driver:'خالد حسن',carrier:'الخليج للنقل',status:'تحميل',value:4100},
    {id:'TRP-1003',customer:'الوطنية لمواد البناء',origin:'الدمام',destination:'جدة',truck:'TRK-041',driver:'سعد فهد',carrier:'المشرق اللوجستية',status:'متأخرة',value:6300},
    {id:'TRP-1004',customer:'الأمانة للتبريد',origin:'جدة',destination:'رابغ',truck:'TRK-009',driver:'بدر محمد',carrier:'ناقل الوطنية',status:'مكتملة',value:2200},
    {id:'TRP-1005',customer:'الشرق للمعدات',origin:'الرياض',destination:'جدة',truck:'TRK-033',driver:'ناصر حمد',carrier:'الخليج للنقل',status:'تفريغ',value:4900}
  ]
};
const money=n=>new Intl.NumberFormat('ar-SA').format(n)+' ر.س';
const badge=s=>`<span class="badge ${s==='متأخرة'?'red':s==='مكتملة'||s==='متاح'?'green':s==='في الطريق'||s==='تفريغ'?'blue':'amber'}">${s}</span>`;
const app=document.getElementById('app');
function shell(){app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">S1</div><div><b>Station One</b><small>ANC Logistics Control Tower</small></div></div><div class="nav">
<button data-page="dashboard">◫ <span>لوحة التحكم</span></button><button data-page="booking">＋ <span>حجز جديد</span><span class="count">${state.bookings.length}</span></button><button data-page="trips">🚚 <span>الرحلات</span></button><button data-page="returns">↻ <span>رحلات العودة</span></button><button data-page="fleet">▤ <span>الأسطول</span></button></div><div class="status"><i></i><span>النظام يعمل — نسخة أولية</span></div></aside><main class="main"><header class="topbar"><div><h1 id="title"></h1><p id="subtitle"></p></div><div class="actions"><span class="chip">الأحد، 27 يوليو 2026</span><button class="btn" onclick="refreshPage()">تحديث</button></div></header><section class="content" id="content"></section></main></div><div id="toast" class="toast"></div>`;document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));go(state.page)}
function go(page){state.page=page;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({dashboard,booking,trips,returns,fleet}[page])()}
function head(t,s){title.textContent=t;subtitle.textContent=s}
function notify(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function refreshPage(){go(state.page);notify('تم تحديث بيانات النظام')}
function dashboard(){head('لوحة التحكم','نظرة شاملة على عمليات النقل اليوم');const revenue=state.trips.reduce((a,x)=>a+x.value,0);content.innerHTML=`<div class="row-between"><span class="live">● البيانات محدثة لحظيًا</span><button class="btn primary" onclick="go('booking')">＋ حجز جديد</button></div><div class="kpis">
${kpi('إجمالي الرحلات','42','↑ 12% عن الأمس','#7b1724')}${kpi('الرحلات المنفذة','35','83% من المستهدف','#2e67b8')}${kpi('قيد التنفيذ','7','تحت المتابعة','#d98a12')}${kpi('إيرادات اليوم',money(revenue),'↑ 9.8% عن المتوسط','#14966f')}${kpi('هامش الربح','28%','↑ 2.3% هذا الشهر','#7b1724')}</div><div class="grid"><div><div class="card"><div class="cardhead"><div><h3>أداء الرحلات والإيرادات</h3><small>Trips & Revenue Performance</small></div><div class="legend"><span><i style="background:#7b1724"></i>الرحلات</span><span><i style="background:#d7a51d"></i>الإيرادات</span></div></div><div class="cardbody"><div class="chart">${[42,58,51,72,66,88,79].map((v,i)=>`<div class="barcol"><div class="barpair"><div class="bar a" style="height:${v}%"></div><div class="bar b" style="height:${Math.max(20,v-16)}%"></div></div>${['8ص','10ص','12م','2م','4م','6م','8م'][i]}</div>`).join('')}</div></div></div><div class="card"><div class="cardhead"><div><h3>الرحلات النشطة</h3><small>Active Trips</small></div><button class="btn" onclick="go('trips')">عرض الكل</button></div>${tripTable(state.trips)}</div></div><div><div class="card"><div class="cardhead"><div><h3>التنبيهات التشغيلية</h3><small>Operational Alerts</small></div><span class="badge red">3 عاجلة</span></div><div class="cardbody alerts"><div class="alert"><div><b>تأخر الرحلة TRP-1003</b><small>تجاوز الموعد 75 دقيقة</small></div><button class="btn" onclick="notify('تم فتح التنبيه')">إجراء</button></div><div class="alert"><div><b>نقص مستند POD</b><small>الرحلة TRP-0984</small></div><button class="btn" onclick="notify('تم إسناد المتابعة')">إجراء</button></div><div class="alert"><div><b>انخفاض وقود TRK-041</b><small>مستوى الوقود 18%</small></div><button class="btn" onclick="notify('تم إخطار السائق')">إجراء</button></div></div></div><div class="card"><div class="cardhead"><div><h3>فرص رحلات العودة</h3><small>Backhaul Opportunities</small></div></div><div class="cardbody"><p style="color:var(--muted);font-size:12px">7 شاحنات ستصل فارغة خلال 6 ساعات.</p><div class="profit">الربح الإضافي المتوقع: 18,400 ر.س</div><button class="btn gold" style="width:100%;margin-top:12px" onclick="go('returns')">تشغيل المطابقة</button></div></div></div></div>`}
function kpi(l,v,f,c){return `<div class="kpi" style="--accent:${c}"><small>${l}</small><strong>${v}</strong><div class="foot"><b>${f}</b></div></div>`}
function tripTable(arr){return `<div class="tablewrap"><table><thead><tr><th>الرحلة</th><th>العميل</th><th>المسار</th><th>الشاحنة</th><th>السائق</th><th>الحالة</th><th>القيمة</th></tr></thead><tbody>${arr.map(t=>`<tr><td class="id">${t.id}</td><td>${t.customer}</td><td>${t.origin} ← ${t.destination}</td><td>${t.truck}</td><td>${t.driver}</td><td>${badge(t.status)}</td><td>${money(t.value)}</td></tr>`).join('')}</tbody></table></div>`}
function booking(){head('حجز جديد','إدخال الطلب وتشغيل المطابقة الذكية');content.innerHTML=`<div class="card"><div class="cardhead"><div><h3>بيانات طلب النقل</h3><small>New Transportation Order</small></div><span class="badge amber">طلب جديد</span></div><div class="cardbody"><div class="form"><div class="field"><label>العميل</label><select id="customer"><option>السعودية للحديد</option><option>الخليج للأغذية</option><option>الوطنية لمواد البناء</option></select></div><div class="field"><label>مدينة التحميل</label><select id="origin"><option>جدة</option><option>الرياض</option><option>الدمام</option><option>رابغ</option></select></div><div class="field"><label>مدينة التسليم</label><select id="destination"><option>الرياض</option><option>جدة</option><option>الدمام</option><option>رابغ</option></select></div><div class="field"><label>نوع الشاحنة</label><select id="type"><option>ثقيل</option><option>مبرد</option><option>سطحة</option></select></div><div class="field"><label>الوزن (طن)</label><input id="weight" type="number" value="15"></div><div class="field"><label>قيمة الرحلة</label><input id="value" type="number" value="5200"></div><div class="field wide"><label>ملاحظات التشغيل</label><textarea id="notes" rows="3" placeholder="تعليمات الموقع أو المتطلبات الخاصة"></textarea></div></div><div class="row-between" style="margin:16px 0 0"><span></span><button class="btn primary" onclick="showMatches()">تشغيل المطابقة الذكية</button></div></div></div><div id="matches"></div>`}
function showMatches(){const cs=[{carrier:'ناقل الوطنية',truck:'TRK-025',driver:'محمد سالم',score:96,profit:1680,reasons:['في مدينة التحميل','نوع الشاحنة مطابق','السائق متاح','تقييم ناقل مرتفع']},{carrier:'الخليج للنقل',truck:'TRK-044',driver:'خالد حسن',score:91,profit:1540,reasons:['جاهزة خلال ساعة','الحمولة مناسبة','تكلفة تشغيل جيدة']},{carrier:'المشرق اللوجستية',truck:'TRK-018',driver:'سعد فهد',score:84,profit:1420,reasons:['مسافة فارغة منخفضة','سائق متاح','سعر تنافسي']}];matches.innerHTML=`<div class="card"><div class="cardhead"><div><h3>أفضل الترشيحات</h3><small>Smart Matching Results</small></div><span class="badge green">3 مؤهلة</span></div><div class="cardbody"><div class="matchgrid">${cs.map((c,i)=>`<div class="match ${i===0?'best':''}">${i===0?'<span class="rank">الأفضل</span>':''}<div class="score">${c.score}%</div><h4>${c.carrier}</h4><p>${c.truck} • السائق: ${c.driver}</p><div class="profit">الربح المتوقع: ${money(c.profit)}</div><ul>${c.reasons.map(r=>`<li>${r}</li>`).join('')}</ul><button class="btn primary" style="width:100%" onclick='approve(${JSON.stringify(c)})'>اعتماد وإسناد</button></div>`).join('')}</div></div></div>`}
function approve(c){state.bookings.unshift({id:'BKG-'+Date.now().toString().slice(-5),customer:customer.value,origin:origin.value,destination:destination.value,truck:c.truck,driver:c.driver,carrier:c.carrier,status:'في الطريق',value:+value.value});localStorage.setItem('s1-bookings',JSON.stringify(state.bookings));notify('تم اعتماد الحجز وإسناد الشاحنة');setTimeout(()=>shell(),400)}
function trips(){head('الرحلات','إدارة ومتابعة الرحلات التشغيلية');const all=[...state.bookings,...state.trips];content.innerHTML=`<div class="card"><div class="toolbar"><input id="search" placeholder="بحث برقم الرحلة أو العميل"><button class="btn primary" onclick="go('booking')">＋ رحلة جديدة</button></div><div id="tripstable">${tripTable(all)}</div></div>`;search.oninput=e=>document.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.innerText.includes(e.target.value)?'':'none')}
function returns(){head('رحلات العودة','تقليل الكيلومترات الفارغة وزيادة الربحية');const rows=[['TRK-025','الرياض','45 دقيقة','ثقيل','12 كم','الرياض ← جدة','5,200 ر.س'],['TRK-041','جدة','ساعتان','مبرد','18 كم','جدة ← الدمام','6,300 ر.س'],['TRK-018','الدمام','3 ساعات','سطحة','25 كم','الدمام ← الرياض','4,100 ر.س']];content.innerHTML=`<div class="row-between"><span class="live">● 7 شاحنات جاهزة للمطابقة</span><button class="btn gold" onclick="notify('تم تشغيل المطابقة الجماعية واكتشاف 11 فرصة')">تشغيل المطابقة الجماعية</button></div><div class="card"><div class="tablewrap"><table><thead><tr><th>الشاحنة</th><th>مدينة الوصول</th><th>الجاهزية</th><th>النوع</th><th>المسافة الفارغة</th><th>أفضل فرصة</th><th>العائد</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}<td><button class="btn primary" onclick="notify('تم اعتماد رحلة العودة')">اعتماد</button></td></tr>`).join('')}</tbody></table></div></div>`}
function fleet(){head('الأسطول','الجاهزية والمواقع والحالة الفنية');const rows=[['TRK-025','أ ب ج 4521','ثقيل','جدة','متاح','25 طن'],['TRK-041','د هـ و 8412','مبرد','الدمام','في الطريق','18 طن'],['TRK-018','س ط ع 1190','سطحة','رابغ','صيانة','30 طن'],['TRK-044','ن م ل 2701','ثقيل','جدة','متاح','25 طن']];content.innerHTML=`<div class="kpis">${kpi('إجمالي الأسطول','42','جميع الناقلين','#7b1724')}${kpi('متاحة الآن','16','جاهزة للإسناد','#14966f')}${kpi('في الطريق','21','تحت المتابعة','#2e67b8')}${kpi('في الصيانة','5','تحتاج متابعة','#d8485b')}</div><div class="card"><div class="tablewrap"><table><thead><tr><th>الشاحنة</th><th>اللوحة</th><th>النوع</th><th>الموقع</th><th>الحالة</th><th>الحمولة</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="id">${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${badge(r[4])}</td><td>${r[5]}</td></tr>`).join('')}</tbody></table></div></div>`}
shell();
