const trips=[
{id:'TR-24071',customer:'المراعي',from:'جدة',to:'الرياض',driver:'أحمد السلمي',truck:'ANC-214',status:'live',statusText:'قيد التنفيذ',progress:68,value:6400,eta:'14:35'},
{id:'TR-24072',customer:'سدافكو',from:'مكة',to:'المدينة',driver:'خالد الحربي',truck:'ANC-118',status:'assigned',statusText:'تم التعيين',progress:22,value:4200,eta:'16:20'},
{id:'TR-24073',customer:'بن زقر',from:'الرياض',to:'جدة',driver:'محمد الزهراني',truck:'GUL-021',status:'pending',statusText:'بانتظار التحميل',progress:8,value:7100,eta:'19:10'},
{id:'TR-24074',customer:'نستله',from:'جدة',to:'الدمام',driver:'فهد المطيري',truck:'ANC-309',status:'issue',statusText:'تنبيه تشغيلي',progress:51,value:8900,eta:'22:40'},
{id:'TR-24075',customer:'النهدي',from:'الدمام',to:'الرياض',driver:'سعود القحطاني',truck:'SHR-144',status:'live',statusText:'قيد التنفيذ',progress:77,value:5300,eta:'13:50'}
];
const matches=[
{rank:1,score:96,carrier:'ANC Logistics',driver:'أحمد السلمي',truck:'ANC-214',distance:'12 كم',return:'عودة مؤكدة',cost:3850,profit:2550,eta:'35 دقيقة',reasons:[['قرب الشاحنة',98],['توفر السائق',100],['رحلة العودة',96],['التكلفة التشغيلية',91],['سجل الالتزام',95]]},
{rank:2,score:91,carrier:'شركة الخليج للنقل',driver:'خالد الحربي',truck:'GUL-021',distance:'24 كم',return:'عودة مرشحة',cost:4020,profit:2380,eta:'52 دقيقة',reasons:[['قرب الشاحنة',90],['توفر السائق',100],['رحلة العودة',88],['التكلفة التشغيلية',89],['سجل الالتزام',92]]},
{rank:3,score:84,carrier:'الشرق للنقليات',driver:'محمد الزهراني',truck:'SHR-144',distance:'39 كم',return:'بدون عودة',cost:4280,profit:2120,eta:'70 دقيقة',reasons:[['قرب الشاحنة',81],['توفر السائق',95],['رحلة العودة',62],['التكلفة التشغيلية',86],['سجل الالتزام',93]]}
];
const fleet=[
{id:'ANC-214',type:'براد 16 طن',location:'جدة - الخمرة',driver:'أحمد السلمي',status:'متاحة',health:94,util:88},
{id:'ANC-118',type:'ستارة جانبية',location:'مكة',driver:'خالد الحربي',status:'في رحلة',health:89,util:91},
{id:'ANC-309',type:'براد 20 طن',location:'طريق الدمام',driver:'فهد المطيري',status:'في رحلة',health:78,util:82},
{id:'ANC-402',type:'سطحة',location:'الرياض',driver:'—',status:'صيانة',health:61,util:69},
{id:'ANC-221',type:'صندوق مغلق',location:'جدة',driver:'سعود القحطاني',status:'متاحة',health:97,util:86}
];
const pageMeta={dashboard:['لوحة التحكم التنفيذية','نظرة شاملة على أداء العمليات اليوم'],operations:['غرفة العمليات','المراقبة المباشرة وإدارة الاستثناءات'],bookings:['إدارة الحجوزات','عرض وتتبع جميع طلبات النقل'],matching:['محرك المطابقة الذكي','ترشيح أفضل ناقل وسائق وشاحنة ورحلة عودة'],trips:['إدارة الرحلات','متابعة دورة حياة الرحلة من الإنشاء حتى الإغلاق'],fleet:['إدارة الأسطول','جاهزية الشاحنات، المواقع والصيانة'],drivers:['إدارة السائقين','التوفر، الأداء، الرخص والامتثال'],carriers:['إدارة الناقلين','الشركاء، الأسعار ومستوى الخدمة'],customers:['إدارة العملاء','الحسابات، العقود والربحية'],reports:['التقارير والتحليلات','مؤشرات الأداء واتجاهات الربحية'],settings:['إعدادات النظام','المستخدمون، الصلاحيات وقواعد المطابقة']};
let charts=[];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return new Intl.NumberFormat('ar-SA').format(n)+' ر.س'}
function icon(name){return `<i data-lucide="${name}"></i>`}
function refreshIcons(){if(window.lucide) lucide.createIcons()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function destroyCharts(){charts.forEach(c=>c.destroy());charts=[]}
function statusClass(s){return `<span class="status ${s}">`}
function pageHead(title,sub,actions=''){return `<div class="page-head"><div><h3>${title}</h3><p>${sub}</p></div><div class="actions">${actions}</div></div>`}

$('#loginBtn').addEventListener('click',()=>{ $('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');renderPage('dashboard');toast('مرحبًا بك في Station One');});
$('#loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')$('#loginBtn').click()});
$('#menuBtn').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$('#closeDrawer').addEventListener('click',closeDrawer);$('#drawerBackdrop').addEventListener('click',closeDrawer);
$('#mainNav').addEventListener('click',e=>{const b=e.target.closest('.nav-item');if(!b)return;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPage(b.dataset.page);$('.sidebar').classList.remove('open')});
$('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')toast(`نتائج البحث عن: ${e.target.value||'الكل'}`)});

function renderPage(page){destroyCharts();const [t,s]=pageMeta[page];$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;const c=$('#pageContainer');
 const renderers={dashboard:renderDashboard,operations:renderOperations,bookings:renderBookings,matching:renderMatching,trips:renderTrips,fleet:renderFleet,drivers:renderDrivers,carriers:renderCarriers,customers:renderCustomers,reports:renderReports,settings:renderSettings};
 c.innerHTML=renderers[page]();refreshIcons();setTimeout(()=>initPage(page),20);window.scrollTo({top:0,behavior:'smooth'});
}
function renderDashboard(){return `${pageHead('أداء اليوم','الأحد، 27 يوليو 2026 — آخر تحديث قبل لحظات',`<button class="btn">${icon('download')} تصدير التقرير</button><button class="btn primary" onclick="openNewBooking()">${icon('plus')} حجز جديد</button>`)}
<div class="kpi-grid">
${kpi('clipboard-check','الحجوزات اليوم','128','+12.5%','مقارنة بالأمس','blue')}
${kpi('route','الرحلات الجارية','42','+8.2%','6 رحلات قاربت الوصول','green')}
${kpi('truck','استغلال الأسطول','89%','+4.1%','من أصل 126 شاحنة','orange')}
${kpi('circle-dollar-sign','إجمالي الربح','184,600 ر.س','+18.4%','هامش 24.7%','purple')}
</div>
<div class="grid-2"><section class="card"><div class="card-head"><div><h4>الحجوزات والتنفيذ</h4><p>آخر 7 أيام</p></div><div class="segmented"><button class="active">أسبوعي</button><button>شهري</button></div></div><div class="chart-wrap"><canvas id="opsChart"></canvas></div></section>
<section class="card"><div class="card-head"><div><h4>حالة الأسطول</h4><p>توزيع 126 شاحنة</p></div><button class="link-btn" onclick="renderPage('fleet')">عرض الأسطول</button></div><div class="donut-wrap"><canvas id="fleetChart"></canvas><div class="donut-center"><strong>126</strong><span>إجمالي الشاحنات</span></div></div></section></div>
<div class="grid-2"><section class="card table-card"><div class="table-toolbar"><div><h4 style="margin:0">الرحلات النشطة</h4><p class="muted" style="margin:2px 0 0;font-size:9px">تحديث لحظي</p></div><button class="link-btn" onclick="renderPage('trips')">عرض الكل</button></div>${tripsTable(trips.slice(0,4))}</section>
<section class="card"><div class="card-head"><div><h4>مركز التنبيهات</h4><p>الأحداث التي تحتاج انتباهك</p></div><span class="status issue">4 تنبيهات</span></div>${activityList()}</section></div>`}
function kpi(ic,label,val,trend,small,color){return `<section class="kpi"><div class="kpi-top"><div class="kpi-icon ${color==='blue'?'':color}">${icon(ic)}</div><span class="trend">${trend}</span></div><strong>${val}</strong><span>${label}</span><small>${small}</small></section>`}
function activityList(){return `<div class="activity-list">
<div class="activity"><div class="activity-icon" style="background:#fff1f0;color:#f04438">${icon('triangle-alert')}</div><div><strong>تأخر متوقع في الرحلة TR-24074</strong><span>ازدحام مرتفع على طريق الدمام — قبل 5 دقائق</span></div></div>
<div class="activity"><div class="activity-icon">${icon('sparkles')}</div><div><strong>تم العثور على رحلة عودة مطابقة</strong><span>جدة ← الرياض بنسبة 96% — قبل 11 دقيقة</span></div></div>
<div class="activity"><div class="activity-icon" style="background:#ecfdf3;color:#12b76a">${icon('badge-check')}</div><div><strong>وصول شحنة المراعي بنجاح</strong><span>تم تأكيد مستند التسليم — قبل 18 دقيقة</span></div></div>
<div class="activity"><div class="activity-icon" style="background:#fff7ed;color:#f79009">${icon('wrench')}</div><div><strong>صيانة دورية قريبة للشاحنة ANC-402</strong><span>متبقي 420 كم — قبل 31 دقيقة</span></div></div></div>`}
function tripsTable(data){return `<table class="data-table"><thead><tr><th>الرحلة</th><th>العميل</th><th>المسار</th><th>السائق / الشاحنة</th><th>الحالة</th><th>التقدم</th><th>القيمة</th><th></th></tr></thead><tbody>${data.map(t=>`<tr><td class="number">${t.id}</td><td>${t.customer}</td><td><div class="route-cell"><span>${t.from}</span><i data-lucide="arrow-left" style="width:14px;color:#98a2b3"></i><span>${t.to}</span></div></td><td><span class="mini-avatar">${t.driver.split(' ')[0][0]}${t.driver.split(' ')[1]?.[0]||''}</span>${t.driver}<div class="muted" style="margin-right:36px">${t.truck}</div></td><td>${statusClass(t.status)}${t.statusText}</span></td><td><div style="display:flex;gap:7px;align-items:center"><div class="progress"><span style="width:${t.progress}%"></span></div><small>${t.progress}%</small></div></td><td class="number">${money(t.value)}</td><td><button class="icon-btn" onclick="openTrip('${t.id}')">${icon('chevron-left')}</button></td></tr>`).join('')}</tbody></table>`}
function renderOperations(){return `${pageHead('مركز العمليات المباشر','42 رحلة جارية • 6 رحلات تتطلب المتابعة',`<span class="status live">متصل مباشر</span><button class="btn">${icon('refresh-cw')} تحديث</button>`)}
<div class="grid-2"><section class="card"><div class="card-head"><div><h4>خريطة العمليات</h4><p>المواقع التقريبية للشاحنات النشطة</p></div><div class="segmented"><button class="active">الكل</button><button>متأخرة</button><button>متاحة</button></div></div><div class="map-panel"><div class="map-route r1"></div><div class="map-route r2"></div><div class="map-node n1">12</div><div class="map-node n2">8</div><div class="map-node n3">6</div><div class="map-node n4">16</div></div></section><section class="card"><div class="card-head"><div><h4>أولوية المتابعة</h4><p>مرتبة حسب درجة المخاطر</p></div></div>${activityList()}</section></div>
<section class="card table-card"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="ابحث في الرحلات المباشرة"></div><div class="actions"><button class="btn small">${icon('filter')} تصفية</button><button class="btn small primary" onclick="openNewBooking()">${icon('plus')} حجز جديد</button></div></div>${tripsTable(trips)}</section>`}
function renderBookings(){return `${pageHead('سجل الحجوزات','128 حجزًا اليوم • 12 بانتظار التعيين',`<button class="btn">${icon('upload')} استيراد</button><button class="btn primary" onclick="openNewBooking()">${icon('plus')} إضافة حجز</button>`)}
<div class="kpi-grid">${kpi('inbox','جديدة','12','+3','منذ ساعة','blue')}${kpi('badge-check','تم تعيينها','96','75%','من إجمالي اليوم','green')}${kpi('clock-3','بانتظار تأكيد','14','-2','تحسن عن الأمس','orange')}${kpi('circle-x','ملغاة','6','1.9%','نسبة الإلغاء','purple')}</div><section class="card table-card"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="رقم الحجز أو العميل"></div><div class="actions"><select class="btn"><option>جميع الحالات</option><option>جديد</option><option>معين</option></select><button class="btn">${icon('download')} تصدير</button></div></div>${tripsTable(trips.concat(trips.slice(0,2).map((t,i)=>({...t,id:'BK-260'+(i+1),status:'pending',statusText:'حجز جديد'}))))}</section>`}
function renderMatching(){return `${pageHead('المطابقة الذكية','أنشئ طلبًا جديدًا واحصل على أفضل الترشيحات خلال ثوانٍ',`<button class="btn">${icon('sliders-horizontal')} أوزان المطابقة</button>`)}<div class="ops-layout"><section class="card booking-form"><div class="card-head"><div><span class="eyebrow">NEW BOOKING</span><h4 style="margin-top:5px">بيانات الحجز الجديد</h4></div><div class="kpi-icon">${icon('clipboard-plus')}</div></div><div class="form-grid">
<div class="field full"><label>العميل</label><select id="mCustomer"><option>شركة المراعي</option><option>سدافكو</option><option>بن زقر</option><option>نستله</option></select></div>
<div class="field"><label>مدينة التحميل</label><select id="mFrom"><option>جدة</option><option>الرياض</option><option>الدمام</option><option>مكة</option></select></div><div class="field"><label>مدينة التسليم</label><select id="mTo"><option>الرياض</option><option>جدة</option><option>الدمام</option><option>المدينة</option></select></div>
<div class="field"><label>تاريخ التحميل</label><input type="date" value="2026-07-28"></div><div class="field"><label>وقت التحميل</label><input type="time" value="09:00"></div>
<div class="field"><label>نوع الشاحنة</label><select><option>براد 16 طن</option><option>ستارة جانبية</option><option>صندوق مغلق</option></select></div><div class="field"><label>الحمولة</label><input value="16 طن"></div>
<div class="field"><label>الأولوية</label><select><option>عاجل</option><option>عادي</option><option>مرن</option></select></div><div class="field"><label>سعر البيع</label><input value="6,400 ر.س"></div>
</div><button id="runMatch" class="btn primary wide" style="margin-top:16px">${icon('sparkles')} تشغيل محرك المطابقة</button><div class="demo-note">${icon('brain-circuit')} يحلل المحرك الموقع، التوفر، التكلفة، رحلة العودة، الأداء والامتثال.</div></section>
<section class="card"><div class="card-head"><div><span class="eyebrow">AI MATCHING RESULTS</span><h4 style="margin-top:5px">أفضل الترشيحات</h4></div><span class="status live">3 نتائج</span></div><div class="match-summary"><div><span class="muted">أفضل نتيجة</span><strong>96%</strong></div><div><span class="muted">الربح المتوقع</span><strong>${money(2550)}</strong></div><div><span class="muted">وقت الاستجابة</span><strong>1.8 ثانية</strong></div></div><div id="matchResults" class="match-list">${matchCards()}</div></section></div>`}
function matchCards(){return matches.map(m=>`<article class="match-card" onclick="openMatch(${m.rank})"><div class="match-score" style="--score:${m.score}%"><div class="match-score-inner"><strong>${m.score}%</strong><span>مطابقة</span></div></div><div class="match-main"><div style="display:flex;align-items:center;gap:8px"><h4>#${m.rank} ${m.carrier}</h4>${m.rank===1?'<span class="chip green">الأفضل</span>':''}</div><div class="muted" style="font-size:10px;margin-bottom:7px">${m.driver} • ${m.truck}</div><div class="match-meta"><span class="chip blue">${icon('map-pin')} ${m.distance}</span><span class="chip green">${icon('route')} ${m.return}</span><span class="chip">${icon('clock')} ${m.eta}</span></div></div><div class="match-finance"><strong>${money(m.profit)}</strong><span>ربح متوقع</span><button class="btn small primary" style="margin-top:8px" onclick="event.stopPropagation();assignMatch(${m.rank})">اعتماد</button></div></article>`).join('')}
function renderTrips(){return `${pageHead('جميع الرحلات','متابعة التشغيل، المستندات والتكلفة الفعلية',`<button class="btn">${icon('calendar-days')} اليوم</button><button class="btn primary" onclick="openNewBooking()">${icon('plus')} رحلة جديدة</button>`)}<div class="kpi-grid">${kpi('play-circle','جارية','42','+6','عن بداية اليوم','blue')}${kpi('check-circle-2','مكتملة','61','94%','تسليم في الوقت','green')}${kpi('clock-alert','متأخرة','4','-1','عن الأمس','orange')}${kpi('file-check-2','مستندات مكتملة','87%','+5%','معدل الإغلاق','purple')}</div><section class="card table-card"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="ابحث برقم الرحلة"></div><div class="actions"><button class="btn small">${icon('filter')} فلترة متقدمة</button></div></div>${tripsTable(trips.concat(trips))}</section>`}
function renderFleet(){return `${pageHead('جاهزية الأسطول','126 شاحنة • 23 متاحة للتعيين الآن',`<button class="btn">${icon('map')} خريطة الأسطول</button><button class="btn primary">${icon('plus')} إضافة شاحنة</button>`)}<div class="kpi-grid">${kpi('truck','إجمالي الأسطول','126','+4','مقارنة بالشهر الماضي','blue')}${kpi('circle-check-big','متاحة','23','18%','جاهزة للتعيين','green')}${kpi('route','في رحلات','91','72%','معدل تشغيل مباشر','orange')}${kpi('wrench','في الصيانة','12','-2','انخفاض الأعطال','purple')}</div><section class="card table-card"><div class="table-toolbar"><div class="table-search">${icon('search')}<input placeholder="رقم الشاحنة أو السائق"></div><div class="actions"><select class="btn"><option>كل الأنواع</option><option>براد</option><option>ستارة</option></select></div></div><table class="data-table"><thead><tr><th>الشاحنة</th><th>النوع</th><th>الموقع</th><th>السائق</th><th>الحالة</th><th>السلامة الفنية</th><th>الاستغلال</th><th></th></tr></thead><tbody>${fleet.map(f=>`<tr><td class="number">${f.id}</td><td>${f.type}</td><td>${icon('map-pin')} ${f.location}</td><td>${f.driver}</td><td><span class="status ${f.status==='متاحة'?'live':f.status==='صيانة'?'issue':'assigned'}">${f.status}</span></td><td><div style="display:flex;gap:8px;align-items:center"><div class="progress"><span style="width:${f.health}%"></span></div>${f.health}%</div></td><td>${f.util}%</td><td><button class="icon-btn" onclick="openFleet('${f.id}')">${icon('chevron-left')}</button></td></tr>`).join('')}</tbody></table></section>`}
function renderDrivers(){return genericPeople('السائقون','184 سائقًا نشطًا • 37 متاحون الآن',['أحمد السلمي','خالد الحربي','محمد الزهراني','فهد المطيري','سعود القحطاني']);}
function renderCarriers(){return genericCompanies('الناقلون الشركاء','26 ناقلًا معتمدًا • متوسط الالتزام 92%',['ANC Logistics','شركة الخليج للنقل','الشرق للنقليات','المسار السريع','الرواد للنقل']);}
function renderCustomers(){return genericCompanies('حسابات العملاء','48 عميلًا نشطًا • 7 عقود قيد التجديد',['المراعي','سدافكو','بن زقر','نستله','النهدي']);}
function genericPeople(title,sub,names){return `${pageHead(title,sub,`<button class="btn primary">${icon('user-plus')} إضافة سائق</button>`)}<div class="kpi-grid">${kpi('users','إجمالي السائقين','184','+8','هذا الشهر','blue')}${kpi('user-check','متاحون الآن','37','20%','من الإجمالي','green')}${kpi('badge-check','التزام المستندات','96%','+2%','عن الشهر السابق','orange')}${kpi('star','متوسط التقييم','4.7','+0.2','من 5','purple')}</div><section class="card table-card"><table class="data-table"><thead><tr><th>السائق</th><th>الجوال</th><th>الموقع</th><th>الشاحنة</th><th>الحالة</th><th>التقييم</th><th>الرحلات</th><th></th></tr></thead><tbody>${names.map((n,i)=>`<tr><td><span class="mini-avatar">${n.split(' ')[0][0]}${n.split(' ')[1][0]}</span><strong>${n}</strong></td><td>05${(51234000+i*3917).toString()}</td><td>${['جدة','الرياض','مكة','الدمام','المدينة'][i]}</td><td>${fleet[i]?.id||'—'}</td><td><span class="status ${i%3===0?'live':'assigned'}">${i%3===0?'متاح':'في رحلة'}</span></td><td>★ ${(4.9-i*.1).toFixed(1)}</td><td>${142-i*13}</td><td><button class="icon-btn">${icon('chevron-left')}</button></td></tr>`).join('')}</tbody></table></section>`}
function genericCompanies(title,sub,names){return `${pageHead(title,sub,`<button class="btn primary">${icon('plus')} إضافة جديد</button>`)}<div class="grid-3">${names.slice(0,3).map((n,i)=>`<section class="card"><div class="card-head"><div><span class="eyebrow">${i===0?'STRATEGIC':'ACTIVE'}</span><h4 style="margin-top:5px">${n}</h4></div><div class="kpi-icon">${icon('building-2')}</div></div><div class="metric-row" style="grid-template-columns:1fr 1fr"><div class="mini-metric"><span>الرحلات الشهرية</span><strong>${420-i*87}</strong></div><div class="mini-metric"><span>الالتزام</span><strong>${96-i*2}%</strong></div></div><div class="progress"><span style="width:${92-i*4}%"></span></div><p class="muted" style="font-size:9px">أداء الحساب ممتاز خلال آخر 30 يومًا</p></section>`).join('')}</div><section class="card table-card" style="margin-top:16px"><table class="data-table"><thead><tr><th>الاسم</th><th>مدير الحساب</th><th>الرحلات</th><th>الإيراد الشهري</th><th>الربحية</th><th>الالتزام</th><th>الحالة</th><th></th></tr></thead><tbody>${names.map((n,i)=>`<tr><td><strong>${n}</strong></td><td>${['عبدالله الغامدي','مراد أحمد','سلام محمد','ناصر علي','فيصل سعد'][i]}</td><td>${420-i*63}</td><td class="number">${money(860000-i*97000)}</td><td>${24-i}%</td><td>${96-i}%</td><td><span class="status live">نشط</span></td><td><button class="icon-btn">${icon('chevron-left')}</button></td></tr>`).join('')}</tbody></table></section>`}
function renderReports(){return `${pageHead('التحليلات التنفيذية','الربحية، الإنتاجية، جودة الخدمة ورحلات العودة',`<button class="btn">${icon('calendar-range')} يوليو 2026</button><button class="btn primary">${icon('download')} تنزيل PDF</button>`)}<div class="kpi-grid">${kpi('circle-dollar-sign','الإيرادات','7.48 م ر.س','+14.2%','مقارنة بالشهر الماضي','blue')}${kpi('wallet-cards','إجمالي الربح','1.86 م ر.س','+18.4%','هامش 24.9%','green')}${kpi('route','رحلات العودة','312','+27%','معدل مطابقة 41%','orange')}${kpi('clock-check','التسليم في الموعد','94.2%','+1.8%','SLA','purple')}</div><div class="grid-2"><section class="card"><div class="card-head"><div><h4>الإيراد والربح</h4><p>آخر 6 أشهر</p></div></div><div class="chart-wrap"><canvas id="revenueChart"></canvas></div></section><section class="card"><div class="card-head"><div><h4>رحلات العودة حسب المسار</h4><p>أعلى 5 مسارات</p></div></div><div class="chart-wrap"><canvas id="returnChart"></canvas></div></section></div>`}
function renderSettings(){return `${pageHead('إعدادات المنصة','تخصيص النظام وقواعد المطابقة',`<button class="btn primary" onclick="toast('تم حفظ الإعدادات بنجاح')">${icon('save')} حفظ التغييرات</button>`)}<div class="grid-2"><section class="card"><div class="card-head"><div><h4>أوزان محرك المطابقة</h4><p>حدد أهمية كل عامل في نتيجة الترشيح</p></div></div>${[['قرب الشاحنة',25],['توفر السائق',20],['وجود رحلة عودة',25],['التكلفة التشغيلية',15],['الالتزام السابق',15]].map(x=>`<div class="score-row" style="margin-bottom:15px"><span>${x[0]}</span><input type="range" min="0" max="40" value="${x[1]}" oninput="this.nextElementSibling.textContent=this.value+'%'"><strong>${x[1]}%</strong></div>`).join('')}</section><section class="card"><div class="card-head"><div><h4>إعدادات التنبيهات</h4><p>تحكم في الحالات التي تظهر بغرفة العمليات</p></div></div>${['تأخر الوصول المتوقع','انخفاض هامش الربح','انتهاء رخصة السائق','موعد صيانة الشاحنة','فشل تحديث الموقع'].map((x,i)=>`<div style="display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)"><div><strong style="font-size:11px">${x}</strong><div class="muted" style="font-size:9px">إرسال إشعار فوري للمستخدمين المعنيين</div></div><input type="checkbox" ${i<4?'checked':''}></div>`).join('')}</section></div>`}
function initPage(page){if(page==='dashboard')initDashboardCharts();if(page==='matching')$('#runMatch').addEventListener('click',()=>{const b=$('#runMatch');b.innerHTML=icon('loader-circle')+' جاري التحليل...';refreshIcons();setTimeout(()=>{b.innerHTML=icon('sparkles')+' تشغيل محرك المطابقة';refreshIcons();$('#matchResults').innerHTML=matchCards();refreshIcons();toast('اكتملت المطابقة: تم العثور على 3 ترشيحات')},900)});if(page==='reports')initReportCharts()}
function chartDefaults(){Chart.defaults.font.family='Cairo';Chart.defaults.color='#667085'}
function initDashboardCharts(){chartDefaults();charts.push(new Chart($('#opsChart'),{type:'line',data:{labels:['الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت','الأحد'],datasets:[{label:'الحجوزات',data:[88,105,96,121,116,134,128],borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.08)',fill:true,tension:.4},{label:'المنفذ',data:[76,92,91,108,105,120,113],borderColor:'#12b76a',backgroundColor:'transparent',tension:.4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'top',align:'end'}},scales:{x:{grid:{display:false}},y:{grid:{color:'#eef2f6'}}}}}));charts.push(new Chart($('#fleetChart'),{type:'doughnut',data:{labels:['في رحلة','متاحة','صيانة'],datasets:[{data:[91,23,12],backgroundColor:['#2563eb','#12b76a','#f79009'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'72%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}}}))}
function initReportCharts(){chartDefaults();charts.push(new Chart($('#revenueChart'),{type:'bar',data:{labels:['فبراير','مارس','أبريل','مايو','يونيو','يوليو'],datasets:[{label:'الإيراد',data:[5.2,5.9,6.1,6.8,7.0,7.48],backgroundColor:'#2563eb',borderRadius:7},{label:'الربح',data:[1.1,1.25,1.31,1.52,1.57,1.86],backgroundColor:'#12b76a',borderRadius:7}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'top',align:'end'}},scales:{x:{grid:{display:false}},y:{grid:{color:'#eef2f6'}}}}}));charts.push(new Chart($('#returnChart'),{type:'bar',data:{labels:['جدة ← الرياض','الرياض ← جدة','الدمام ← الرياض','جدة ← الدمام','المدينة ← جدة'],datasets:[{label:'رحلات العودة',data:[84,71,55,48,39],backgroundColor:['#2563eb','#3b82f6','#60a5fa','#93c5fd','#bfdbfe'],borderRadius:7}]},options:{indexAxis:'y',responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{color:'#eef2f6'}},y:{grid:{display:false}}}}}))}
function openDrawer(title,html){$('#drawerTitle').textContent=title;$('#drawerContent').innerHTML=html;$('#detailsDrawer').classList.add('open');$('#drawerBackdrop').classList.remove('hidden');refreshIcons()}
function closeDrawer(){$('#detailsDrawer').classList.remove('open');$('#drawerBackdrop').classList.add('hidden')}
function openTrip(id){const t=trips.find(x=>x.id===id)||trips[0];openDrawer(t.id,`<div class="alert-box">${icon('radio')} تحديث مباشر — الوصول المتوقع ${t.eta}</div><div class="detail-section"><h4>بيانات الرحلة</h4><div class="detail-grid">${[['العميل',t.customer],['المسار',t.from+' ← '+t.to],['السائق',t.driver],['الشاحنة',t.truck],['القيمة',money(t.value)],['الحالة',t.statusText]].map(x=>`<div class="detail-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></div><div class="detail-section"><h4>التتبع الزمني</h4><div class="timeline"><div class="time-item"><strong>تم إنشاء الرحلة</strong><span>08:12 ص</span></div><div class="time-item"><strong>تم التعيين والانطلاق</strong><span>09:05 ص</span></div><div class="time-item"><strong>اجتياز نقطة المتابعة</strong><span>11:40 ص</span></div><div class="time-item"><strong>الوصول المتوقع</strong><span>${t.eta}</span></div></div></div><button class="btn primary wide" onclick="toast('تم فتح شاشة المتابعة المباشرة')">${icon('map-pin')} متابعة مباشرة</button>`)}
function openMatch(rank){const m=matches.find(x=>x.rank===rank);openDrawer(`نتيجة المطابقة #${rank}`,`<div class="metric-row"><div class="mini-metric"><span>نسبة المطابقة</span><strong>${m.score}%</strong></div><div class="mini-metric"><span>التكلفة</span><strong>${money(m.cost)}</strong></div><div class="mini-metric"><span>الربح</span><strong>${money(m.profit)}</strong></div><div class="mini-metric"><span>الوصول</span><strong>${m.eta}</strong></div></div><div class="detail-section"><h4>المورد المرشح</h4><div class="detail-grid">${[['الناقل',m.carrier],['السائق',m.driver],['الشاحنة',m.truck],['المسافة',m.distance],['رحلة العودة',m.return],['حالة الامتثال','مكتمل']].map(x=>`<div class="detail-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></div><div class="detail-section"><h4>تفسير النتيجة</h4><div class="score-bars">${m.reasons.map(r=>`<div class="score-row"><span>${r[0]}</span><div class="progress"><span style="width:${r[1]}%"></span></div><strong>${r[1]}%</strong></div>`).join('')}</div></div><button class="btn primary wide" onclick="assignMatch(${rank});closeDrawer()">${icon('badge-check')} اعتماد الترشيح</button>`)}
function assignMatch(rank){toast(`تم اعتماد الترشيح رقم ${rank} وإرسال إشعار التعيين`)}
function openFleet(id){const f=fleet.find(x=>x.id===id);openDrawer(id,`<div class="detail-section"><h4>بيانات الشاحنة</h4><div class="detail-grid">${[['النوع',f.type],['الموقع',f.location],['السائق',f.driver],['الحالة',f.status],['السلامة الفنية',f.health+'%'],['الاستغلال',f.util+'%']].map(x=>`<div class="detail-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}</div></div><div class="alert-box">${icon('wrench')} الصيانة القادمة بعد 1,240 كم</div><button class="btn primary wide">${icon('map-pin')} عرض الموقع المباشر</button>`)}
function openNewBooking(){renderPage('matching');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page==='matching'))}
refreshIcons();
